--PERSONEL TABLOSUNDA GOREVÝ HADEME OLAN PERSONELLERÝN MAAÞI 3000'DEN 3200'E GÜNCELLENDÝ
UPDATE Personel
SET Maas=3200 WHERE GorevId in (Select id from Gorev Where Ad = 'Hademe');


--PERSONEL TABLOSUNDA 2900 TL ALTINDA ÇALIÞAN PERSONELLER 9 NUMARALI MÜZEYE ATANDI
UPDATE Personel
SET MuzeId=9 WHERE Personel.Maas < 2900;

--ÖÐRENCÝ BÝLET TÜRÜNÜN FÝYATI 20 LÝRADAN 26 LÝRAYA GÜNCELLENDÝ
UPDATE BiletTuru
SET Ücret=26 WHERE Ad='Öðrenci';

--MUZE TABLOSUNDA ADRESÝ VATÝKAN OLAN MÜZENÝN YAZ SEZONU ACILIS TARÝHÝ 2021-05-05'DEN 2021-06-06'YA GÜNCELLENDÝ
UPDATE Muze
SET YazSezonuAcilis='2021-06-06' WHERE Adres='Vatikan';

--KÝRA TABLOSUNDA KÝRALANAN HER ESERÝN TOPLAM KÝRA SÜRESÝ DATEDIFF KULLANILARAK HESAPLANDI VE GÜNCELLENDÝ
ALTER TABLE Kira
ADD KiraSuresi int;
GO
UPDATE Kira
SET KiraSuresi=DATEDIFF(YEAR,BaslangicTarihi,BitisTarihi);

--KÝRA TABLOSUNDA KÝRALANAN ESERLERÝN KÝRA SÜRESÝ EÐER 4 YILI GEÇMÝÞSSE ÜCRETLERÝ 40000 OLARAK GÜNCELLENDÝ
UPDATE Kira
SET Ücret=40000 WHERE KiraSuresi>3

--MARCO ÝSÝMLÝ KAÞÝFÝN ESERLERÝNÝN ETLKÝNLÝK ÝDSÝ 3 OLARAK GÜNCELLENDÝ
UPDATE Eser
SET EtkinlikId = 3 WHERE Eser.KesifId in ( Select id From Kaþif Where Kaþif.Ad = 'Marco')

--PERSONEL TABLOSUNDAKÝ HER PERSONELÝN CALISMA SÜRESÝ ÝSEBASLAMA TARÝHÝ BAZ ALINARAK DATEDIFF ÝLE HESAPLANDI VE GÜNCELLENDÝ
ALTER TABLE Personel
ADD CalismaSuresi int;
GO
UPDATE Personel
SET CalismaSuresi=DATEDIFF(YEAR,IseBaslamaTarihi,GETDATE());

--PERSONEL TABLOSUNDA CALISMA SÜRESÝ 1 YIL VE 1 YILDAN DAHA AZ OLAN PERSONELLER 4 NUMARALI MÜZEYE ATANDI 
UPDATE Personel
SET MuzeId=4 WHERE CalismaSuresi<=1;

--KAÞÝF TABLOSUNDAKÝ KAÞÝFLERÝN ÖLÜM YAÞLARI DOGUM TARÝHLERÝ VE OLUM TARÝHLERÝ BAZ ALINARAK DATEDIFF ÝLE HESAPLANDI VE ÖLÜM YAÞI SÜTUNUNA ATANDI
ALTER TABLE Kaþif
ADD OlumYasi int;
GO
UPDATE Kaþif
SET OlumYasi=DATEDIFF(YEAR,DogumTarihi,OlumTarihi);



